
// This file has been generated by the GUI designer. Do not modify.
namespace MemoryBlocks
{
	public partial class MainWindow
	{
		private global::Gtk.UIManager UIManager;
		
		private global::Gtk.Action GameAction;
		
		private global::Gtk.Action actGame;
		
		private global::Gtk.Action actNewGame;
		
		private global::Gtk.Action actEasy;
		
		private global::Gtk.Action actModerate;
		
		private global::Gtk.Action actHard;
		
		private global::Gtk.Action actHelp;
		
		private global::Gtk.Action diAbout;
		
		private global::Gtk.Action actRetry;
		
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.MenuBar menuBar;
		
		private global::Gtk.DrawingArea daInfoBar;
		
		private global::Gtk.DrawingArea daTable;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MemoryBlocks.MainWindow
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
			this.GameAction = new global::Gtk.Action ("GameAction", global::Mono.Unix.Catalog.GetString ("Game"), null, null);
			this.GameAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Game");
			w1.Add (this.GameAction, null);
			this.actGame = new global::Gtk.Action ("actGame", global::Mono.Unix.Catalog.GetString ("Game"), null, null);
			this.actGame.ShortLabel = global::Mono.Unix.Catalog.GetString ("Game");
			w1.Add (this.actGame, null);
			this.actNewGame = new global::Gtk.Action ("actNewGame", global::Mono.Unix.Catalog.GetString ("New Game"), null, "gtk-new");
			this.actNewGame.ShortLabel = global::Mono.Unix.Catalog.GetString ("New Game");
			w1.Add (this.actNewGame, null);
			this.actEasy = new global::Gtk.Action ("actEasy", global::Mono.Unix.Catalog.GetString ("Easy"), null, null);
			this.actEasy.ShortLabel = global::Mono.Unix.Catalog.GetString ("Easy");
			w1.Add (this.actEasy, null);
			this.actModerate = new global::Gtk.Action ("actModerate", global::Mono.Unix.Catalog.GetString ("Moderate"), null, null);
			this.actModerate.ShortLabel = global::Mono.Unix.Catalog.GetString ("Moderate");
			w1.Add (this.actModerate, null);
			this.actHard = new global::Gtk.Action ("actHard", global::Mono.Unix.Catalog.GetString ("Hard"), null, null);
			this.actHard.ShortLabel = global::Mono.Unix.Catalog.GetString ("Hard");
			w1.Add (this.actHard, null);
			this.actHelp = new global::Gtk.Action ("actHelp", global::Mono.Unix.Catalog.GetString ("Help"), null, null);
			this.actHelp.ShortLabel = global::Mono.Unix.Catalog.GetString ("Help");
			w1.Add (this.actHelp, null);
			this.diAbout = new global::Gtk.Action ("diAbout", global::Mono.Unix.Catalog.GetString ("About"), null, "gtk-dialog-info");
			this.diAbout.ShortLabel = global::Mono.Unix.Catalog.GetString ("About");
			w1.Add (this.diAbout, null);
			this.actRetry = new global::Gtk.Action ("actRetry", global::Mono.Unix.Catalog.GetString ("Retry"), null, "gtk-undo");
			this.actRetry.ShortLabel = global::Mono.Unix.Catalog.GetString ("Retry");
			w1.Add (this.actRetry, null);
			this.UIManager.InsertActionGroup (w1, 0);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.Name = "MemoryBlocks.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("MemoryBlocks");
			this.Icon = global::Gdk.Pixbuf.LoadFromResource ("MemoryBlocks.Resources.memoryblocks.ico");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			this.Gravity = ((global::Gdk.Gravity)(5));
			// Container child MemoryBlocks.MainWindow.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			// Container child vbox2.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><menubar name='menuBar'><menu name='actGame' action='actGame'><menu name='actNewGame' action='actNewGame'><menuitem name='actEasy' action='actEasy'/><menuitem name='actModerate' action='actModerate'/><menuitem name='actHard' action='actHard'/></menu><menuitem name='actRetry' action='actRetry'/></menu><menu name='actHelp' action='actHelp'><menuitem name='diAbout' action='diAbout'/></menu></menubar></ui>");
			this.menuBar = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menuBar")));
			this.menuBar.Name = "menuBar";
			this.vbox2.Add (this.menuBar);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.menuBar]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.daInfoBar = new global::Gtk.DrawingArea ();
			this.daInfoBar.HeightRequest = 64;
			this.daInfoBar.Name = "daInfoBar";
			this.vbox2.Add (this.daInfoBar);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.daInfoBar]));
			w3.Position = 1;
			// Container child vbox2.Gtk.Box+BoxChild
			this.daTable = new global::Gtk.DrawingArea ();
			this.daTable.WidthRequest = 480;
			this.daTable.HeightRequest = 480;
			this.daTable.Name = "daTable";
			this.vbox2.Add (this.daTable);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.daTable]));
			w4.Position = 2;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 480;
			this.DefaultHeight = 567;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.actEasy.Activated += new global::System.EventHandler (this.OnActEasyActivated);
			this.actModerate.Activated += new global::System.EventHandler (this.OnActModerateActivated);
			this.actHard.Activated += new global::System.EventHandler (this.OnActHardActivated);
			this.diAbout.Activated += new global::System.EventHandler (this.OnDiAboutActivated);
			this.actRetry.Activated += new global::System.EventHandler (this.OnActRetryActivated);
			this.daTable.ButtonPressEvent += new global::Gtk.ButtonPressEventHandler (this.OnDaTableButtonPressEvent);
		}
	}
}
